version: '1.0.{build}'
image: Visual Studio 2017
environment:
  nodejs_version: "12"

pull_requests:
  # Do not increment build number when it is a pull request
  do_not_increment_build_number: true
dotnet_csproj:
  # change assembly versions
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install scripts. (runs after repo cloning)
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
  # install choco tools
  - choco install codecov
build_script:
  - cmd: dotnet publish ./src/MentorBot.Functions/MentorBot.Functions.csproj -c Release
  - cmd: dotnet publish ./src/MentorBot.WebLearningCenter/MentorBot.WebLearningCenter.csproj -c Release
after_build:
  # For once the build has completed
artifacts:
 - path: '\src\MentorBot.Functions\bin\Release\netcoreapp2.2\publish'
   name: MentorBotApi
   type: WebDeployPackage
 - path: '\src\MentorBot.WebLearningCenter\bin\Release\netcoreapp2.2\publish'
   name: MentorBotWebLearningCenter
   type: WebDeployPackage
clone_depth: 1
# to run your custom scripts instead of automatic tests
test_script:
  - cmd: dotnet test ./tests/MentorBot.Tests/MentorBot.Tests.csproj -c Debug -l Appveyor /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByFile=\"../../src/MentorBot.Functions/Models/**/*.cs\"
  - cmd: npm run lint --prefix ./src/MentorBot.WebLearningCenter/ClientApp
  - cmd: npm run test:prod --prefix ./src/MentorBot.WebLearningCenter/ClientApp
  - cmd: codecov -f ./tests/MentorBot.Tests/coverage.opencover.xml
  - cmd: codecov -f ./src/MentorBot.WebLearningCenter/ClientApp/coverage/coverage.lcov
on_finish :
  # any cleanup in here
deploy:
- provider: Environment
  name: DevMentorBotApi
  on:
    branch: master
- provider: Environment
  name: DevMentorBotStaticSite
  on:
    branch: master
