name: super linter
on:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v4.2.2
        env:
          FILTER_REGEX_EXCLUDE: \bLICENSE$|\blog\.txt$
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_ES: false
          LOG_LEVEL: WARN
