name: Lint Code Base
on:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: github/super-linter@v4.8.1
        env:
          FILTER_REGEX_EXCLUDE: \bLICENSE$
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_YAML: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          LOG_LEVEL: WARN
